# Generated by Django 5.0.4 on 2024-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("league", models.CharField(max_length=255)),
                ("season", models.IntegerField()),
                ("team1", models.CharField(max_length=255)),
                ("team2", models.CharField(max_length=255)),
                ("spi1", models.FloatField()),
                ("spi2", models.FloatField()),
                ("prob1", models.FloatField()),
                ("prob2", models.FloatField()),
                ("probtie", models.FloatField()),
                ("proj_score1", models.FloatField()),
                ("proj_score2", models.FloatField()),
                ("score1", models.IntegerField()),
                ("score2", models.IntegerField()),
            ],
            options={
                "db_table": "matches",
            },
        ),
    ]
