name: Prettier

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install Prettier
      run: npm install prettier@3.3.3

    - name: Run Prettier
      run: npm run prettier
